[project]
name = 'GreenChain'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.rec-issuance]
path = 'contracts/rec-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.rec-marketplace]
path = 'contracts/rec-marketplace.clar'
clarity_version = 2
epoch = 2.5

[contracts.rec-token]
path = 'contracts/rec-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
